### ISSUE TITLE
Servicename connection string

### ISSUE THREAD

**Issue by dwwilde** [daparker/pending-banner-releases#1]
The three oracle connection strings in the java file need to be modified to the service name format to allow the program to connect to pluggable databases (and RAC dbs).

From:
"jdbc:oracle:thin:@%s:%s:%s"
To:
"jdbc:oracle:thin:@//%s:%s/%s"

**Comment by daparker** [comment]
Thanks for reporting this issue.  It works with our pluggable databases on Oracle 19c, but I think that's because we have `USE_SID_AS_SERVICE_LISTENER = on` specified in our $ORACLE_HOME/network/admin/listener.ora file.  You could try adding that to your listener.ora file and restarting the listener to see if it helps.

I will add a config option in the next release to select which thin client connection string to use.

**Comment by daparker** [comment]
@dwwilde I believe this issue should now be fixed in v1.4.0.  For the JDBC connection, it will try the CDB/PDB/RAC compatible format first, then fall back to the old format if that doesn't work.  Please let me know if you continue to see this issue, or if any other come up. Thanks!

**Comment by daparker** [comment]
Fixed in version 1.4.0.

**Comment by dwwilde** [comment]
1.4.0 works with service name connections.   Thanks for the update.
